project:
  type: website
  output-dir: docs/
  
website:
  title: "Mateusz Rzeszutek"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 1_experience.qmd
        text: Experience
      - text: Science
        menu: 
          - 2a_scientific.qmd
          - 2b_industry.qmd
          - 2c_administration.qmd
          - 2d_r_fortran.qmd
          - 2e_conferences.qmd
      - href: 3_certificated.qmd
        text: Certificated
      - href: 4_teaching.qmd
        text: Teaching
      - href: 5_prizes.qmd
        text: Prizes
      - href: CV.pdf
        text: CV

    right:
      - about.qmd
      - icon: activity
        href: http://www.scopus.com/inward/authorDetails.url?authorID=57193075220&partnerID=MN8TOARS
      - icon: github
        href: https://github.com/mrzeszut
      - icon: youtube
        href: https://www.youtube.com/@MateuszRk
      - icon: bicycle
        href: https://www.strava.com/athletes/117075897
      - icon: linkedin
        href: https://www.linkedin.com/in/mateusz-rzeszutek-612187152/
      - icon: person
        href: https://www.researchgate.net/profile/Mateusz-Rzeszutek-2
      - icon: journal-bookmark-fill
        href: https://orcid.org/0000-0002-0488-4435
        
format:
  html:
    theme: solar
    css: styles.css
    
editor: source

